apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-frontend
  namespace: kafka-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-frontend
  template:
    metadata:
      labels:
        app: stats-frontend
    spec:
      containers:
      - name: stats-frontend
        image: ondrejnr1/stats-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stats-frontend
  namespace: kafka-web
spec:
  selector:
    app: stats-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
